### PR TITLE
Add basic integration tests

### PR DESCRIPTION
**Pull request by surrealbytes**
#6
this is some basic testing i used before touching the code, wanted to add more but didn't make it,
i will mark this as work in progress until it's ready for merging
i may not be able to work on this until next weekend.

a Testing section after contributing may be useful as well.

the Pipfile has a `dev` section too for packages that are needed only when developing, the noise on Pipfile.lock is just packages for testing that come with pytest and a plugin for auto-running the tests called pytest-watch.

### CODE REVIEW

**Comment by surrealbytes** [comment]
i think this is okay for starters, it will be easier to refactor the code with a least some acceptance tests.
we will need unittests in the future.

@dellitsni can you and run them?
you will need to download the geckodriver,
are you developing on Linux or windows?

**Comment by dellitsni** [comment]
@surrealbytes This looks great, I'll give it a try and review when i get home. I'm on KDE Neon.

**Comment by dellitsni** [comment]
Might just be me who's confused, but shouldn't test_user_story.py end with something that actually launches the tests, so it can be executed from a shell easily? Such as:

if __name__ = '__main__':
    pytest.main()

There's also some issues with the browser hanging at certain points, which has made it impossible for me to complete a test. I can't seem to figure out why. 

It hangs on line 90, 94 and 130. Just loads forever, until the test fails, then it loads immediately. I'll try to test on my Windows desktop and see if i can reproduce there. 

@surrealbytes

**Comment by surrealbytes** [comment]
The tests should run with just running `pytest` in the root path of the project. pytest has test detection on files and functions that start with `test_`.

I had some issues with selenium as well, something like losing focus of the selenium window or resizing made the test fail for me. Also if the response takes time the test also seem to fail.

These tests will need a refactor too at some point, when we have enough unittests we can remove specific tests from these.

**Comment by dellitsni** [comment]
@surrealbytes Alright, I'll merge now, we can always fix the random test failures later on. Nice to finally be free of manual testing.

**Pull request merged**
