### PR TITLE
Testfix

### PR DESCRIPTION
**Pull request by surrealbytes**

### CODE REVIEW

**Comment by dellitsni** [comment]
The "progresses in x" value isn't being shown properly in phase 2.

**Comment by surrealbytes** [comment]
@dellitsni okay i've refactored the code some, can you give it another try?

**Comment by dellitsni** [comment]
That looks really clean, much better. Everything works now too. Good work!

By the way, Konsent is online at http://konsent.xyz now! I'm working on getting SSL with Let's Encrypt, will make a post on Raddle when it's ready. I've made a Konsent Developers union just for fun to test things out, the password is "correcthorsebatterystaple" if you wanna join.

**Comment by dellitsni** [comment]
@surrealbytes Hey, you found a bug already. Your post completely skipped phase 2. :thinking:

I think threading is disabled on PythonAnywhere, which makes apscheduler go crazy, I'll see what i can do about it.

**Comment by surrealbytes** [comment]
yeah just noticed that, no idea why that happends. disabled threading? :(

**Comment by surrealbytes** [comment]
i feel like i've introduced a bug

**Comment by surrealbytes** [comment]
it seems that locally it works thought :man_shrugging:

**Comment by surrealbytes** [comment]
now it works on pythonanywhere too? wtf :laughing: 

i got some 'Internal Errors'  from pythoneverywhere but can't reproduce reliably.

**Comment by surrealbytes** [comment]
maybe make update happen every 60seconds so we don't put too much load on the server?

**Comment by dellitsni** [comment]
Yeah it's weird, I'm getting it too. The error log says "The MySQL server has gone away". Not very helpful.

I don't think the phases are going to update either, there's some work to do still.

**Comment by dellitsni** [comment]
Got it fixed! Now we just need SSL and a way to update the phases.

**Pull request merged**
