### PR TITLE
PythonAnywhere

### PR DESCRIPTION
**Pull request by surrealbytes**
this PR targets the master branch not the develop

### CODE REVIEW

**Comment by dellitsni** [comment]
How do we run it now? `__main__.py` is completely empty, except for an import that isn't being used. Or am i missing something?

**Comment by surrealbytes** [comment]
you run it but invoking `konsent`, oh you want to run it with `python konsent` ? i will add the ifmain clause again

**Comment by surrealbytes** [comment]
when we import main from cli, click does the dirty job

**Comment by dellitsni** [comment]
Perfect, thanks. I'll merge it, good work.

**Comment by surrealbytes** [comment]
yea whatever you want. i will be able to work on this in the afternoon.

**Pull request merged**
