### PR TITLE
Allow authors to configure the resting time when posting new issues

### PR DESCRIPTION
**Pull request by dellitsni**
#21 

Trying to figure out what the best way is for inputting resting time. Right now it accepts only minutes, which is sort of problematic (having to pull out a calculator to figure out the resting time sucks). I'll remove the WIP tag when I've figured something out. 

The commit history is a mess, sorry about that.

### CODE REVIEW

**Comment by surrealbytes** [comment]
We should probably use seconds to represent resting time in the database as you usually do or even datetime objects, not sure how MySQL handles those. How the user will configure this is independent, we will do the calculations, the user may only see a calendar or whatever.

**Comment by surrealbytes** [comment]
we should also consider the fact that some issues won't have an expiration.

**Comment by dellitsni** [comment]
Right, I'll make it seconds. How would posts without a resting time work? They have to progress to the next phase somehow.

**Comment by surrealbytes** [comment]
consensus or other ways we can't think now.

**Comment by dellitsni** [comment]
Oh, right. In that case we could just set resting time to zero.

**Pull request merged**
