### PR TITLE
Replaced hashlib with bcrypt

### PR DESCRIPTION
**Pull request by dellitsni**
#26 

Replaced hashlib with the much more secure bcrypt.

### CODE REVIEW

**Comment by surrealbytes** [comment]
is there a reason to put the `bcrypt` stuff in `models.py` ? the database should really know only the hash always.

**Comment by dellitsni** [comment]
Actually... I'm not sure how I'd go about moving bcrypt out of models. It might just be me having one of those moments, but the password from the database is required to hash and compare the password from the form. I have a feeling that I'm making an embarassing late-night mistake here..

**Comment by surrealbytes** [comment]
It's okay :) we ca do that later, i would just move all the hashing related stuff to the Flask views and ever only pass the hash to the models.

**Comment by surrealbytes** [comment]
getting this atm:

```
ValueError: Invalid salt
```

**Pull request merged**
