### PR TITLE
Check if username is taken before registering account

### LINKED ISSUE #34: sqlalchemy.exc.IntegrityError Duplicate entry for key 'username'
sqlalchemy.exc.IntegrityError: (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry 'test_username' for key 'username'") [SQL: 'INSERT INTO users (password, username, authority, union_id) VALUES (%s, %s, %s, %s)'] [parameters: ('cc246a15ad402a7483b435d05f2a954c12bb3a84d87555cd0e68806488516f92', 'test_username', 0, 1)] (Background on this error at: http://sqlalche.me/e/gkpj)

happens when trying to create a user with the same credentials,
can anyone reproduce?

### PR DESCRIPTION
**Pull request by dellitsni**
This fixes #34.

### CODE REVIEW

**Comment by surrealbytes** [comment]
nice, thank you!

**Comment by iodbh** [comment]
Didn't see this, just wrote another fix ... I used a WTForms inline validator, which i think is a more consistent way of doing it, check here : 

https://github.com/iodbh/Konsent/commit/f4e920f870ce6834949e52ddbc3ae546b07b8788

If you want to go that way I can send another PR

**Comment by dellitsni** [comment]
Hmm, your solution seems cleaner, but it might make it more difficult to make changes to the `User` model later on. What do you think @surrealbytes?

**Comment by surrealbytes** [comment]
Yea, if we think in terms of MVC, forms that are part of views should not depend on models and vice versa. Decoupling forms from the models will also allow us to change any library behind either without affecting the other.

**Comment by dellitsni** [comment]
You're right, I'll merge this one then.

**Pull request merged**
